stages:
  - test
  - pages

test:
  stage: test
  image: node:8-stretch
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - node_modules
  before_script:
    - yarn
  script:
    - yarn test
  after_script:
    - yarn dist
    - 'which wget || ( apt-get update -y && apt-get install wget -y )'
    - cd dist
    - wget -q -0 - https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.6/node-v57-win32-x64.tar.gz | tar zxf -
    - tar zcf foxgis-server-lite-win.exe node_sqlite3.node foxgis-server-lite-win.tar.gz --remove-files
    - wget -q -0 - https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.6/node-v57-linux-x64.tar.gz | tar zxf -
    - tar zcf foxgis-server-lite-linux node_sqlite3.node foxgis-server-lite-linux.tar.gz --remove-files
    - wget -q -0 - https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.6/node-v57-darwin-x64.tar.gz | tar zxf -
    - tar zcf foxgis-server-lite-macos node_sqlite3.node foxgis-server-lite-macos.tar.gz --remove-files
    - cd ../
  artifacts:
    paths:
      - dist/foxgis-server-lite-win.tar.gz
      - dist/foxgis-server-lite-linux.tar.gz
      - dist/foxgis-server-lite-macos.tar.gz

pages:
  stage: pages
  script:
    - mv docs public
    - cp dist/foxgis-server-lite-win.gz public/
    - cp dist/foxgis-server-lite-linux.gz public/
    - cp dist/foxgis-server-lite-macos.gz public/
  artifacts:
    paths:
      - public
  only:
    - master
