stages:
  - test
  - pages

test:
  stage: test
  image: node:8-stretch
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - node_modules
  before_script:
    - yarn
  script:
    - yarn test
  after_script:
    - yarn dist
    - 'which wget || ( apt-get update -y && apt-get install wget -y )'
    - wget -q -O - https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.6/node-v57-win32-x64.tar.gz | tar zxf -
    - wget -q -O - https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.6/node-v57-linux-x64.tar.gz | tar zxf -
    - wget -q -O - https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.6/node-v57-darwin-x64.tar.gz | tar zxf -
    - mkdir -p foxgis-server-lite-win foxgis-server-lite-linux foxgis-server-lite-macos
    - mv dist/foxgis-server-lite-win.exe node-v57-win32-x64/node_sqlite3.node foxgis-server-lite-win/
    - mv dist/foxgis-server-lite-linux node-v57-linux-x64/node_sqlite3.node foxgis-server-lite-linux/
    - mv dist/foxgis-server-lite-macos node-v57-darwin-x64/node_sqlite3.node foxgis-server-lite-macos/
    - cp -R data foxgis-server-lite-win/
    - cp -R data foxgis-server-lite-linux/
    - cp -R data foxgis-server-lite-macos/
    - tar zcf foxgis-server-lite-win.tar.gz foxgis-server-lite-win
    - tar zcf foxgis-server-lite-linux.tar.gz foxgis-server-lite-linux
    - tar zcf foxgis-server-lite-macos.tar.gz foxgis-server-lite-macos
  artifacts:
    paths:
      - foxgis-server-lite-win.tar.gz
      - foxgis-server-lite-linux.tar.gz
      - foxgis-server-lite-macos.tar.gz

pages:
  stage: pages
  script:
    - mkdir -p public
    - mv docs/* foxgis-server-lite-win.tar.gz foxgis-server-lite-linux.tar.gz foxgis-server-lite-macos.tar.gz public/
  artifacts:
    paths:
      - public
  only:
    - master
