name: Node CI
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 8

    - name: Test
      run: |
        yarn
        yarn test
      env:
        CI: true

    - name: Build
      run: |
        yarn dist
        wget -q -O - https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.1/node-v57-win32-x64.tar.gz | tar zxf -
        wget -q -O - https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.1/node-v57-linux-x64.tar.gz | tar zxf -
        wget -q -O - https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.1/node-v57-darwin-x64.tar.gz | tar zxf -
        mkdir -p foxgis-server-lite-win foxgis-server-lite-linux foxgis-server-lite-macos
        mv dist/foxgis-server-lite-win.exe node-v57-win32-x64/node_sqlite3.node foxgis-server-lite-win/
        mv dist/foxgis-server-lite-linux node-v57-linux-x64/node_sqlite3.node foxgis-server-lite-linux/
        mv dist/foxgis-server-lite-macos node-v57-darwin-x64/node_sqlite3.node foxgis-server-lite-macos/
        cp -R data foxgis-server-lite-win/
        cp -R data foxgis-server-lite-linux/
        cp -R data foxgis-server-lite-macos/
        tar zcf foxgis-server-lite-win.tar.gz foxgis-server-lite-win
        tar zcf foxgis-server-lite-linux.tar.gz foxgis-server-lite-linux
        tar zcf foxgis-server-lite-macos.tar.gz foxgis-server-lite-macos
        mv foxgis-server-lite-win.tar.gz foxgis-server-lite-linux.tar.gz foxgis-server-lite-macos.tar.gz docs/

    - name: GitHub Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: docs
